#!/bin/bash

export PROJECT_DIR="/opt/forticlientsslvpn"

VPN_URI='fortisslvpn.example.com:10443'
VPN_USER='login'
VPN_PASS='password'

if [[ $EUID -ne 0 ]]; then
    echo "This program must be run as root"
    exit 1
fi

cat /etc/resolv.conf > /etc/resolv.conf-org

if [[ -z "$VPN_URI" ]] || [[ -z "$VPN_USER" ]] || [[ -z "$VPN_PASS" ]]
then
  echo "[!] Please, provide the following environment variables:"
  echo '    - VPN_URI (in the form of FQDN:PORT)'
  echo '    - VPN_USER'
  echo '    - VPN_PASS'
  exit 1
fi

expect <<EOF
spawn $PROJECT_DIR/64bit/forticlientsslvpn_cli --server $VPN_URI --vpnuser $VPN_USER --keepalive
while (1) {
  expect {
    -re ".*Password for VPN.*" { send "${VPN_PASS/$/\\$}\r" }
    -re ".*Would you like to connect to this server?.*" { send "Y\r" }
    eof { break }
  }
}
EOF

cat /etc/resolv.conf-org > /etc/resolv.conf
