#!/bin/bash

set -x
export PROJECT_DIR="$( cd $(dirname $(readlink -f $(which forticlientsslvpn_cli)))/.. && pwd  )"

#VPN_URI=_VPN_URI_
#VPN_USER=_VPN_USER_
#VPN_PASS=_VPN_PASS_

if [[ -z "$VPN_URI" ]] || [[ -z "$VPN_USER" ]] || [[ -z "$VPN_PASS" ]]
then
  echo "[!] Please, provide the following environment variables:"
  echo '    - $VPN_URI (in the form of ${HOST}:${PORT})'
  echo '    - $VPN_USER'
  echo '    - $VPN_PASS'
  exit 1
fi

expect <<EOF
spawn $PROJECT_DIR/64bit/forticlientsslvpn_cli --server $VPN_URI --vpnuser $VPN_USER --keepalive
while (1) {
  expect {
    -re ".*Password for VPN.*" { send "${VPN_PASS/$/\\$}\r" }
    -re ".*Would you like to connect to this server?.*" { send "Y\r" }
    eof { break }
  }
}
EOF
